### ISSUE TITLE
Notebook IAM tokens are not refreshing

### ISSUE THREAD

**Issue by stthoom** [awslabs/aws-orbit-workbench#707] opened 2021-06-23 21:45 UTC
botocore.errorfactory.ExpiredTokenException: An error occurred (ExpiredTokenException) when calling the AssumeRoleWithWebIdentity operation: Token expired: current date/time 1624482533 must be before the expiration date/time1624482335

**Comment by NickCorbett** [comment] 2021-07-28 15:37
duplicate of #771

**Closed by NickCorbett** 2021-07-28 15:37 UTC
Labels: bug
