### ISSUE TITLE
Orbit credential expired

### ISSUE THREAD

**Issue by yinweisu** [awslabs/aws-orbit-workbench#890] opened 2021-08-09 17:57 UTC
Both kubectl get pods and aws s3 ls results in unauthorized error:
```
jovyan@test-0:~$ kubectl get pods
error: You must be logged in to the server (Unauthorized)
jovyan@test-0:~$ aws s3 ls

An error occurred (ExpiredTokenException) when calling the AssumeRoleWithWebIdentity operation: Token expired: current date/time 1628529916 must be before the expiration date/time1628372266
```

**Comment by yinweisu** [comment] 2021-08-09 17:58
@srinivasreddych Created an issue for you to track

**Comment by srinivasreddych** [comment] 2021-09-08 15:08
The credentials have been expired due to partial deployment which happened. Closing it here, as the issue is resolved

**Closed by srinivasreddych** 2021-09-08 15:08 UTC
Labels: bug
